// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd_operational_mode.proto

#include "cmd_operational_mode.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace badbot {
namespace messages {
class CommandOperationalModeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CommandOperationalMode> _instance;
} _CommandOperationalMode_default_instance_;
}  // namespace messages
}  // namespace badbot
static void InitDefaultsscc_info_CommandOperationalMode_cmd_5foperational_5fmode_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::badbot::messages::_CommandOperationalMode_default_instance_;
    new (ptr) ::badbot::messages::CommandOperationalMode();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::badbot::messages::CommandOperationalMode::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CommandOperationalMode_cmd_5foperational_5fmode_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_CommandOperationalMode_cmd_5foperational_5fmode_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_cmd_5foperational_5fmode_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_cmd_5foperational_5fmode_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_cmd_5foperational_5fmode_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_cmd_5foperational_5fmode_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::badbot::messages::CommandOperationalMode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::badbot::messages::CommandOperationalMode, opmode_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::badbot::messages::CommandOperationalMode)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::badbot::messages::_CommandOperationalMode_default_instance_),
};

const char descriptor_table_protodef_cmd_5foperational_5fmode_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032cmd_operational_mode.proto\022\017badbot.mes"
  "sages\032\014consts.proto\"J\n\026CommandOperationa"
  "lMode\0220\n\006opMode\030\001 \001(\0162 .badbot.messages."
  "OperationalModeb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_cmd_5foperational_5fmode_2eproto_deps[1] = {
  &::descriptor_table_consts_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_cmd_5foperational_5fmode_2eproto_sccs[1] = {
  &scc_info_CommandOperationalMode_cmd_5foperational_5fmode_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_cmd_5foperational_5fmode_2eproto_once;
static bool descriptor_table_cmd_5foperational_5fmode_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cmd_5foperational_5fmode_2eproto = {
  &descriptor_table_cmd_5foperational_5fmode_2eproto_initialized, descriptor_table_protodef_cmd_5foperational_5fmode_2eproto, "cmd_operational_mode.proto", 143,
  &descriptor_table_cmd_5foperational_5fmode_2eproto_once, descriptor_table_cmd_5foperational_5fmode_2eproto_sccs, descriptor_table_cmd_5foperational_5fmode_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_cmd_5foperational_5fmode_2eproto::offsets,
  file_level_metadata_cmd_5foperational_5fmode_2eproto, 1, file_level_enum_descriptors_cmd_5foperational_5fmode_2eproto, file_level_service_descriptors_cmd_5foperational_5fmode_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_cmd_5foperational_5fmode_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_cmd_5foperational_5fmode_2eproto), true);
namespace badbot {
namespace messages {

// ===================================================================

void CommandOperationalMode::InitAsDefaultInstance() {
}
class CommandOperationalMode::_Internal {
 public:
};

CommandOperationalMode::CommandOperationalMode()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:badbot.messages.CommandOperationalMode)
}
CommandOperationalMode::CommandOperationalMode(const CommandOperationalMode& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  opmode_ = from.opmode_;
  // @@protoc_insertion_point(copy_constructor:badbot.messages.CommandOperationalMode)
}

void CommandOperationalMode::SharedCtor() {
  opmode_ = 0;
}

CommandOperationalMode::~CommandOperationalMode() {
  // @@protoc_insertion_point(destructor:badbot.messages.CommandOperationalMode)
  SharedDtor();
}

void CommandOperationalMode::SharedDtor() {
}

void CommandOperationalMode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CommandOperationalMode& CommandOperationalMode::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CommandOperationalMode_cmd_5foperational_5fmode_2eproto.base);
  return *internal_default_instance();
}


void CommandOperationalMode::Clear() {
// @@protoc_insertion_point(message_clear_start:badbot.messages.CommandOperationalMode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  opmode_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* CommandOperationalMode::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .badbot.messages.OperationalMode opMode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          set_opmode(static_cast<::badbot::messages::OperationalMode>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool CommandOperationalMode::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:badbot.messages.CommandOperationalMode)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .badbot.messages.OperationalMode opMode = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_opmode(static_cast< ::badbot::messages::OperationalMode >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:badbot.messages.CommandOperationalMode)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:badbot.messages.CommandOperationalMode)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void CommandOperationalMode::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:badbot.messages.CommandOperationalMode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .badbot.messages.OperationalMode opMode = 1;
  if (this->opmode() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      1, this->opmode(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:badbot.messages.CommandOperationalMode)
}

::PROTOBUF_NAMESPACE_ID::uint8* CommandOperationalMode::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:badbot.messages.CommandOperationalMode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .badbot.messages.OperationalMode opMode = 1;
  if (this->opmode() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->opmode(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:badbot.messages.CommandOperationalMode)
  return target;
}

size_t CommandOperationalMode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:badbot.messages.CommandOperationalMode)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .badbot.messages.OperationalMode opMode = 1;
  if (this->opmode() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->opmode());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CommandOperationalMode::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:badbot.messages.CommandOperationalMode)
  GOOGLE_DCHECK_NE(&from, this);
  const CommandOperationalMode* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CommandOperationalMode>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:badbot.messages.CommandOperationalMode)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:badbot.messages.CommandOperationalMode)
    MergeFrom(*source);
  }
}

void CommandOperationalMode::MergeFrom(const CommandOperationalMode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:badbot.messages.CommandOperationalMode)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.opmode() != 0) {
    set_opmode(from.opmode());
  }
}

void CommandOperationalMode::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:badbot.messages.CommandOperationalMode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandOperationalMode::CopyFrom(const CommandOperationalMode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:badbot.messages.CommandOperationalMode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandOperationalMode::IsInitialized() const {
  return true;
}

void CommandOperationalMode::InternalSwap(CommandOperationalMode* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(opmode_, other->opmode_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CommandOperationalMode::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace badbot
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::badbot::messages::CommandOperationalMode* Arena::CreateMaybeMessage< ::badbot::messages::CommandOperationalMode >(Arena* arena) {
  return Arena::CreateInternal< ::badbot::messages::CommandOperationalMode >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
