// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpsdata.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_gpsdata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_gpsdata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_gpsdata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_gpsdata_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gpsdata_2eproto;
namespace badbot {
namespace messages {
class GpsData;
class GpsDataDefaultTypeInternal;
extern GpsDataDefaultTypeInternal _GpsData_default_instance_;
}  // namespace messages
}  // namespace badbot
PROTOBUF_NAMESPACE_OPEN
template<> ::badbot::messages::GpsData* Arena::CreateMaybeMessage<::badbot::messages::GpsData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace badbot {
namespace messages {

// ===================================================================

class GpsData :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:badbot.messages.GpsData) */ {
 public:
  GpsData();
  virtual ~GpsData();

  GpsData(const GpsData& from);
  GpsData(GpsData&& from) noexcept
    : GpsData() {
    *this = ::std::move(from);
  }

  inline GpsData& operator=(const GpsData& from) {
    CopyFrom(from);
    return *this;
  }
  inline GpsData& operator=(GpsData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GpsData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GpsData* internal_default_instance() {
    return reinterpret_cast<const GpsData*>(
               &_GpsData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GpsData& a, GpsData& b) {
    a.Swap(&b);
  }
  inline void Swap(GpsData* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GpsData* New() const final {
    return CreateMaybeMessage<GpsData>(nullptr);
  }

  GpsData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GpsData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GpsData& from);
  void MergeFrom(const GpsData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GpsData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "badbot.messages.GpsData";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_gpsdata_2eproto);
    return ::descriptor_table_gpsdata_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLatitudeFieldNumber = 1,
    kLongitudeFieldNumber = 2,
    kHdopFieldNumber = 3,
    kVdopFieldNumber = 4,
    kPdopFieldNumber = 5,
    kSatellitesVisibleFieldNumber = 6,
    kSatellitesUsedFieldNumber = 7,
  };
  // double latitude = 1;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);

  // double longitude = 2;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);

  // double hdop = 3;
  void clear_hdop();
  double hdop() const;
  void set_hdop(double value);

  // double vdop = 4;
  void clear_vdop();
  double vdop() const;
  void set_vdop(double value);

  // double pdop = 5;
  void clear_pdop();
  double pdop() const;
  void set_pdop(double value);

  // int32 satellites_visible = 6;
  void clear_satellites_visible();
  ::PROTOBUF_NAMESPACE_ID::int32 satellites_visible() const;
  void set_satellites_visible(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 satellites_used = 7;
  void clear_satellites_used();
  ::PROTOBUF_NAMESPACE_ID::int32 satellites_used() const;
  void set_satellites_used(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:badbot.messages.GpsData)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  double latitude_;
  double longitude_;
  double hdop_;
  double vdop_;
  double pdop_;
  ::PROTOBUF_NAMESPACE_ID::int32 satellites_visible_;
  ::PROTOBUF_NAMESPACE_ID::int32 satellites_used_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_gpsdata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GpsData

// double latitude = 1;
inline void GpsData::clear_latitude() {
  latitude_ = 0;
}
inline double GpsData::latitude() const {
  // @@protoc_insertion_point(field_get:badbot.messages.GpsData.latitude)
  return latitude_;
}
inline void GpsData::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.GpsData.latitude)
}

// double longitude = 2;
inline void GpsData::clear_longitude() {
  longitude_ = 0;
}
inline double GpsData::longitude() const {
  // @@protoc_insertion_point(field_get:badbot.messages.GpsData.longitude)
  return longitude_;
}
inline void GpsData::set_longitude(double value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.GpsData.longitude)
}

// double hdop = 3;
inline void GpsData::clear_hdop() {
  hdop_ = 0;
}
inline double GpsData::hdop() const {
  // @@protoc_insertion_point(field_get:badbot.messages.GpsData.hdop)
  return hdop_;
}
inline void GpsData::set_hdop(double value) {
  
  hdop_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.GpsData.hdop)
}

// double vdop = 4;
inline void GpsData::clear_vdop() {
  vdop_ = 0;
}
inline double GpsData::vdop() const {
  // @@protoc_insertion_point(field_get:badbot.messages.GpsData.vdop)
  return vdop_;
}
inline void GpsData::set_vdop(double value) {
  
  vdop_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.GpsData.vdop)
}

// double pdop = 5;
inline void GpsData::clear_pdop() {
  pdop_ = 0;
}
inline double GpsData::pdop() const {
  // @@protoc_insertion_point(field_get:badbot.messages.GpsData.pdop)
  return pdop_;
}
inline void GpsData::set_pdop(double value) {
  
  pdop_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.GpsData.pdop)
}

// int32 satellites_visible = 6;
inline void GpsData::clear_satellites_visible() {
  satellites_visible_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GpsData::satellites_visible() const {
  // @@protoc_insertion_point(field_get:badbot.messages.GpsData.satellites_visible)
  return satellites_visible_;
}
inline void GpsData::set_satellites_visible(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  satellites_visible_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.GpsData.satellites_visible)
}

// int32 satellites_used = 7;
inline void GpsData::clear_satellites_used() {
  satellites_used_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GpsData::satellites_used() const {
  // @@protoc_insertion_point(field_get:badbot.messages.GpsData.satellites_used)
  return satellites_used_;
}
inline void GpsData::set_satellites_used(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  satellites_used_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.GpsData.satellites_used)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace badbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_gpsdata_2eproto
