// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obj_det_coords.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_obj_5fdet_5fcoords_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_obj_5fdet_5fcoords_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_obj_5fdet_5fcoords_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_obj_5fdet_5fcoords_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_obj_5fdet_5fcoords_2eproto;
namespace badbot {
namespace messages {
class Coords;
class CoordsDefaultTypeInternal;
extern CoordsDefaultTypeInternal _Coords_default_instance_;
class ObjectDetectionCoords;
class ObjectDetectionCoordsDefaultTypeInternal;
extern ObjectDetectionCoordsDefaultTypeInternal _ObjectDetectionCoords_default_instance_;
}  // namespace messages
}  // namespace badbot
PROTOBUF_NAMESPACE_OPEN
template<> ::badbot::messages::Coords* Arena::CreateMaybeMessage<::badbot::messages::Coords>(Arena*);
template<> ::badbot::messages::ObjectDetectionCoords* Arena::CreateMaybeMessage<::badbot::messages::ObjectDetectionCoords>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace badbot {
namespace messages {

// ===================================================================

class Coords :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:badbot.messages.Coords) */ {
 public:
  Coords();
  virtual ~Coords();

  Coords(const Coords& from);
  Coords(Coords&& from) noexcept
    : Coords() {
    *this = ::std::move(from);
  }

  inline Coords& operator=(const Coords& from) {
    CopyFrom(from);
    return *this;
  }
  inline Coords& operator=(Coords&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Coords& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Coords* internal_default_instance() {
    return reinterpret_cast<const Coords*>(
               &_Coords_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Coords& a, Coords& b) {
    a.Swap(&b);
  }
  inline void Swap(Coords* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Coords* New() const final {
    return CreateMaybeMessage<Coords>(nullptr);
  }

  Coords* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Coords>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Coords& from);
  void MergeFrom(const Coords& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Coords* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "badbot.messages.Coords";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_obj_5fdet_5fcoords_2eproto);
    return ::descriptor_table_obj_5fdet_5fcoords_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kYFieldNumber = 1,
    kXFieldNumber = 2,
    kHFieldNumber = 3,
    kWFieldNumber = 4,
    kConfidenceFieldNumber = 5,
    kObjIdFieldNumber = 6,
  };
  // int32 y = 1;
  void clear_y();
  ::PROTOBUF_NAMESPACE_ID::int32 y() const;
  void set_y(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 x = 2;
  void clear_x();
  ::PROTOBUF_NAMESPACE_ID::int32 x() const;
  void set_x(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 h = 3;
  void clear_h();
  ::PROTOBUF_NAMESPACE_ID::int32 h() const;
  void set_h(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 w = 4;
  void clear_w();
  ::PROTOBUF_NAMESPACE_ID::int32 w() const;
  void set_w(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 confidence = 5;
  void clear_confidence();
  ::PROTOBUF_NAMESPACE_ID::int32 confidence() const;
  void set_confidence(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 objId = 6;
  void clear_objid();
  ::PROTOBUF_NAMESPACE_ID::int32 objid() const;
  void set_objid(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:badbot.messages.Coords)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_;
  ::PROTOBUF_NAMESPACE_ID::int32 h_;
  ::PROTOBUF_NAMESPACE_ID::int32 w_;
  ::PROTOBUF_NAMESPACE_ID::int32 confidence_;
  ::PROTOBUF_NAMESPACE_ID::int32 objid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_obj_5fdet_5fcoords_2eproto;
};
// -------------------------------------------------------------------

class ObjectDetectionCoords :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:badbot.messages.ObjectDetectionCoords) */ {
 public:
  ObjectDetectionCoords();
  virtual ~ObjectDetectionCoords();

  ObjectDetectionCoords(const ObjectDetectionCoords& from);
  ObjectDetectionCoords(ObjectDetectionCoords&& from) noexcept
    : ObjectDetectionCoords() {
    *this = ::std::move(from);
  }

  inline ObjectDetectionCoords& operator=(const ObjectDetectionCoords& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectDetectionCoords& operator=(ObjectDetectionCoords&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ObjectDetectionCoords& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ObjectDetectionCoords* internal_default_instance() {
    return reinterpret_cast<const ObjectDetectionCoords*>(
               &_ObjectDetectionCoords_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ObjectDetectionCoords& a, ObjectDetectionCoords& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectDetectionCoords* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ObjectDetectionCoords* New() const final {
    return CreateMaybeMessage<ObjectDetectionCoords>(nullptr);
  }

  ObjectDetectionCoords* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ObjectDetectionCoords>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ObjectDetectionCoords& from);
  void MergeFrom(const ObjectDetectionCoords& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectDetectionCoords* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "badbot.messages.ObjectDetectionCoords";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_obj_5fdet_5fcoords_2eproto);
    return ::descriptor_table_obj_5fdet_5fcoords_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCoordinatesFieldNumber = 1,
    kObjectAtAngleFieldNumber = 2,
  };
  // repeated .badbot.messages.Coords coordinates = 1;
  int coordinates_size() const;
  void clear_coordinates();
  ::badbot::messages::Coords* mutable_coordinates(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::badbot::messages::Coords >*
      mutable_coordinates();
  const ::badbot::messages::Coords& coordinates(int index) const;
  ::badbot::messages::Coords* add_coordinates();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::badbot::messages::Coords >&
      coordinates() const;

  // int32 object_at_angle = 2;
  void clear_object_at_angle();
  ::PROTOBUF_NAMESPACE_ID::int32 object_at_angle() const;
  void set_object_at_angle(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:badbot.messages.ObjectDetectionCoords)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::badbot::messages::Coords > coordinates_;
  ::PROTOBUF_NAMESPACE_ID::int32 object_at_angle_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_obj_5fdet_5fcoords_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Coords

// int32 y = 1;
inline void Coords::clear_y() {
  y_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Coords::y() const {
  // @@protoc_insertion_point(field_get:badbot.messages.Coords.y)
  return y_;
}
inline void Coords::set_y(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.Coords.y)
}

// int32 x = 2;
inline void Coords::clear_x() {
  x_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Coords::x() const {
  // @@protoc_insertion_point(field_get:badbot.messages.Coords.x)
  return x_;
}
inline void Coords::set_x(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.Coords.x)
}

// int32 h = 3;
inline void Coords::clear_h() {
  h_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Coords::h() const {
  // @@protoc_insertion_point(field_get:badbot.messages.Coords.h)
  return h_;
}
inline void Coords::set_h(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  h_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.Coords.h)
}

// int32 w = 4;
inline void Coords::clear_w() {
  w_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Coords::w() const {
  // @@protoc_insertion_point(field_get:badbot.messages.Coords.w)
  return w_;
}
inline void Coords::set_w(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  w_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.Coords.w)
}

// int32 confidence = 5;
inline void Coords::clear_confidence() {
  confidence_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Coords::confidence() const {
  // @@protoc_insertion_point(field_get:badbot.messages.Coords.confidence)
  return confidence_;
}
inline void Coords::set_confidence(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  confidence_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.Coords.confidence)
}

// int32 objId = 6;
inline void Coords::clear_objid() {
  objid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Coords::objid() const {
  // @@protoc_insertion_point(field_get:badbot.messages.Coords.objId)
  return objid_;
}
inline void Coords::set_objid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  objid_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.Coords.objId)
}

// -------------------------------------------------------------------

// ObjectDetectionCoords

// repeated .badbot.messages.Coords coordinates = 1;
inline int ObjectDetectionCoords::coordinates_size() const {
  return coordinates_.size();
}
inline void ObjectDetectionCoords::clear_coordinates() {
  coordinates_.Clear();
}
inline ::badbot::messages::Coords* ObjectDetectionCoords::mutable_coordinates(int index) {
  // @@protoc_insertion_point(field_mutable:badbot.messages.ObjectDetectionCoords.coordinates)
  return coordinates_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::badbot::messages::Coords >*
ObjectDetectionCoords::mutable_coordinates() {
  // @@protoc_insertion_point(field_mutable_list:badbot.messages.ObjectDetectionCoords.coordinates)
  return &coordinates_;
}
inline const ::badbot::messages::Coords& ObjectDetectionCoords::coordinates(int index) const {
  // @@protoc_insertion_point(field_get:badbot.messages.ObjectDetectionCoords.coordinates)
  return coordinates_.Get(index);
}
inline ::badbot::messages::Coords* ObjectDetectionCoords::add_coordinates() {
  // @@protoc_insertion_point(field_add:badbot.messages.ObjectDetectionCoords.coordinates)
  return coordinates_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::badbot::messages::Coords >&
ObjectDetectionCoords::coordinates() const {
  // @@protoc_insertion_point(field_list:badbot.messages.ObjectDetectionCoords.coordinates)
  return coordinates_;
}

// int32 object_at_angle = 2;
inline void ObjectDetectionCoords::clear_object_at_angle() {
  object_at_angle_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ObjectDetectionCoords::object_at_angle() const {
  // @@protoc_insertion_point(field_get:badbot.messages.ObjectDetectionCoords.object_at_angle)
  return object_at_angle_;
}
inline void ObjectDetectionCoords::set_object_at_angle(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  object_at_angle_ = value;
  // @@protoc_insertion_point(field_set:badbot.messages.ObjectDetectionCoords.object_at_angle)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace badbot

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_obj_5fdet_5fcoords_2eproto
