# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "shared-storage",
    srcs = ["sharedstrings.cpp","sharedstrings.hpp"],
    hdrs = ["sharedstrings.hpp"],
    include_prefix = "sharedstorage",
    visibility = ["//visibility:public"]
)