# gst-launch-1.0 tcpclientsrc host=localhost port=8998 ! jpegdec ! videoconvert ! xvimagesink

camfeed:
  #https://github.com/gabime/spdlog/pull/622/files
  #define SPDLOG_LEVEL_NAMES { "trace", "debug", "info", "warning", "error", "critical", "off" }
  log_level: trace
  log_format: '%H:%M:%S.%e|%20!n|%^%L%$|%5t| %v'
  console_logger_enabled: true

appsink:
  pipeline: 'v4l2src device=/dev/video2 ! 'image/jpeg,framerate=30/1,width=1280,height=720' ! jpegparse ! jpegdec ! tee name=t ! queue ! videoscale ! 'video/x-raw,width=640,height=480' ! videoconvert ! 'video/x-raw,width=640,height=480,format=BGR,framerate=30/1' ! appsink drop=true max-buffers=1 name=appSink t. ! queue leaky=2 ! x264enc tune=zerolatency ! 'video/x-h264,stream-format=byte-stream,width=(int)1280, height=(int)720, framerate=30/1' ! rtph264pay mtu=1400 pt=96 ! udpsink host=127.0.0.1 port=5000'
  height: 480
  width: 640
