cc_test (
    name = "kalman1",
    srcs = [
        "kalman1_test.cpp",
    ],
    deps = [
        "//shared/filters:kalman",
        "@gtest//:gtest",
        "@gtest//:gtest_main" # Only if hello_test.cc has no main()
    ],
)
